import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

import {Mulish} from 'next/font/google';
import Herosection from "@/app/components/Herosection";
import Footer from "@/app/components/Footer";
const mulish = Mulish( {
        weight: '400',
        subsets: ['latin'],
        display: 'swap',
    })
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
